name: Sanity
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
env:
  GTEST_OUTPUT: xml:./
jobs:
  check-main-push:
    runs-on: ubuntu-22.04
    outputs:
      is-main-push: ${{ steps.check-state.outputs.is-main-push }}
    steps:
      - name: Check State
        id: check-state
        run: |
          if [ "$GITHUB_EVENT_NAME" = 'push' ] && [ "$GITHUB_REF_NAME" = 'main' ]; then \
            echo "::set-output name=is-main-push::1"; \
          else \
            echo "::set-output name=is-main-push::0"; \
          fi

  check-diffs:
    runs-on: ubuntu-22.04
    outputs:
      cli-changed: ${{ steps.check-diffs.outputs.cli-changed }}
      code-changed: ${{ steps.check-diffs.outputs.code-changed }}
      daemon-changed: ${{ steps.check-diffs.outputs.daemon-changed }}
      docs-changed: ${{ steps.check-diffs.outputs.docs-changed }}
      gtk-changed: ${{ steps.check-diffs.outputs.gtk-changed }}
      mac-changed: ${{ steps.check-diffs.outputs.mac-changed }}
      qt-changed: ${{ steps.check-diffs.outputs.qt-changed }}
      tests-changed: ${{ steps.check-diffs.outputs.tests-changed }}
      utils-changed: ${{ steps.check-diffs.outputs.utils-changed }}
      web-changed: ${{ steps.check-diffs.outputs.web-changed }}
    steps:
      - name: Get Source
        id: get-source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: src
          submodules: recursive
      - name: Check for diffs
        id: check-diffs
        run: |
          set +e
          git -C "${GITHUB_WORKSPACE}/src" diff --quiet origin/main -- CMakeLists.txt third-party libtransmission cli
          echo "::set-output name=cli-changed::$?"
          git -C "${GITHUB_WORKSPACE}/src" diff --quiet origin/main -- CMakeLists.txt libtransmission cli daemon gtk macos qt utils tests web
          echo "::set-output name=code-changed::$?"
          git -C "${GITHUB_WORKSPACE}/src" diff --quiet origin/main -- CMakeLists.txt third-party libtransmission daemon
          echo "::set-output name=daemon-changed::$?"
          git -C "${GITHUB_WORKSPACE}/src" diff --quiet origin/main -- docs
          echo "::set-output name=docs-changed::$?"
          git -C "${GITHUB_WORKSPACE}/src" diff --quiet origin/main -- CMakeLists.txt third-party libtransmission gtk
          echo "::set-output name=gtk-changed::$?"
          git -C "${GITHUB_WORKSPACE}/src" diff --quiet origin/main -- CMakeLists.txt third-party libtransmission macosx Transmission.xcodeproj
          echo "::set-output name=mac-changed::$?"
          git -C "${GITHUB_WORKSPACE}/src" diff --quiet origin/main -- CMakeLists.txt third-party libtransmission qt
          echo "::set-output name=qt-changed::$?"
          git -C "${GITHUB_WORKSPACE}/src" diff --quiet origin/main -- CMakeLists.txt third-party libtransmission utils tests
          echo "::set-output name=tests-changed::$?"
          git -C "${GITHUB_WORKSPACE}/src" diff --quiet origin/main -- CMakeLists.txt third-party libtransmission utils
          echo "::set-output name=utils-changed::$?"
          git -C "${GITHUB_WORKSPACE}/src" diff --quiet origin/main -- CMakeLists.txt third-party libtransmission web
          echo "::set-output name=web-changed::$?"
          set -e

  what-to-build:
    runs-on: ubuntu-22.04
    needs: [ check-diffs, check-main-push ]
    outputs:
      build-cli: ${{ needs.check-main-push.outputs.is-main-push == '1' || needs.check-diffs.outputs.cli-changed == '1' }}
      build-code: ${{ needs.check-main-push.outputs.is-main-push == '1' || needs.check-diffs.outputs.code-changed == '1' }}
      build-daemon: ${{ needs.check-main-push.outputs.is-main-push == '1' || needs.check-diffs.outputs.daemon-changed == '1' }}
      build-docs: ${{ needs.check-main-push.outputs.is-main-push == '1' || needs.check-diffs.outputs.docs-changed == '1' }}
      build-gtk: ${{ needs.check-main-push.outputs.is-main-push == '1' || needs.check-diffs.outputs.gtk-changed == '1' }}
      build-mac: ${{ needs.check-main-push.outputs.is-main-push == '1' || needs.check-diffs.outputs.mac-changed == '1' }}
      build-qt: ${{ needs.check-main-push.outputs.is-main-push == '1' || needs.check-diffs.outputs.qt-changed == '1' }}
      build-tests: ${{ needs.check-main-push.outputs.is-main-push == '1' || needs.check-diffs.outputs.tests-changed == '1' }}
      build-utils: ${{ needs.check-main-push.outputs.is-main-push == '1' || needs.check-diffs.outputs.utils-changed == '1' }}
      build-web: ${{ needs.check-main-push.outputs.is-main-push == '1' || needs.check-diffs.outputs.web-changed == '1' }}
    steps:
      - name: Canary
        run: |
          echo '${{ toJSON(needs) }}'

  code-style:
    runs-on: ubuntu-22.04
    needs: [ what-to-build ]
    if: needs.what-to-build.outputs.build-code
    steps:
      - name: Canary
        run: |
          echo '${{ toJSON(needs) }}'
      - name: Get Source
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Get Dependencies
        run: |
          sudo apt-get install clang-format-12 npm yarn
      - name: Check for style diffs
        id: check-for-diffs
        working-directory: .
        run: |
          ./code_style.sh
          set +e
          git diff --exit-code > style.diff
          echo "::set-output name=differs::$?"
          cat style.diff
          set -e
      - name: Upload Diffs
        uses: actions/upload-artifact@v2
        if: steps.check-for-diffs.outputs.differs == '1'
        with:
          name: code-style.diff
          path: 'style.diff'
      - name: Fail if diffs exist
        if: steps.check-for-diffs.outputs.differs == '1'
        run: |
          exit 1

  sanitizer-tests:
    runs-on: ubuntu-22.04
    needs: [ what-to-build ]
    if: needs.what-to-build.outputs.build-tests
    steps:
      - name: Get Dependencies
        run: |
          set -ex
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            ca-certificates \
            clang \
            cmake \
            gettext \
            libcurl4-openssl-dev \
            libdeflate-dev \
            libevent-dev \
            libfmt-dev \
            libminiupnpc-dev \
            libnatpmp-dev \
            libpsl-dev \
            libssl-dev \
            ninja-build
      - name: Get Source
        uses: actions/checkout@v3
        with:
          submodules: recursive
          path: src
      - name: Configure
        run: |
          cmake \
            -S src \
            -B obj \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_CXX_COMPILER='clang++' \
            -DCMAKE_CXX_FLAGS='-gdwarf-4 -fno-omit-frame-pointer -fsanitize=address,leak,undefined' \
            -DCMAKE_C_COMPILER='clang' \
            -DCMAKE_C_FLAGS='-gdwarf-4 -fno-omit-frame-pointer -fsanitize=address,leak,undefined' \
            -DCMAKE_INSTALL_PREFIX=pfx \
            -DENABLE_CLI=OFF \
            -DENABLE_GTK=OFF \
            -DENABLE_QT=OFF \
            -DRUN_CLANG_TIDY=OFF
      - name: Make
        run: cmake --build obj --config Debug --target libtransmission-test transmission-show
      - name: Test with sanitizers
        run: cmake -E chdir obj ctest --build-config Debug --output-on-failure

  macos:
    runs-on: macos-latest
    needs: [ what-to-build ]
    if: needs.what-to-build.outputs.build-cli || needs.what-to-build.outputs.build-gtk || needs.what-to-build.outputs.build-mac || needs.what-to-build.outputs.build-qt
    steps:
      - name: Get Dependencies
        run: |
          set -ex
          brew install \
            cmake \
            gettext \
            gtkmm3 \
            libdeflate \
            libevent \
            libnatpmp \
            libpsl \
            miniupnpc \
            ninja \
            qt@5
      - name: Get Source
        uses: actions/checkout@v3
        with:
          path: src
          submodules: recursive
      - name: Configure
        run: |
          cmake \
            -S src \
            -B obj \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_INSTALL_PREFIX=pfx \
            -DCMAKE_OSX_ARCHITECTURES='x86_64' \
            -DCMAKE_OSX_DEPLOYMENT_TARGET='10.10' \
            -DCMAKE_PREFIX_PATH=`brew --prefix`/opt/qt@5 \
            -DENABLE_CLI=${{ needs.what-to-build.outputs.build-cli && 'ON' || 'OFF' }} \
            -DENABLE_GTK=${{ needs.what-to-build.outputs.build-gtk && 'ON' || 'OFF' }} \
            -DENABLE_MAC=${{ needs.what-to-build.outputs.build-mac && 'ON' || 'OFF' }}  \
            -DENABLE_QT=${{ needs.what-to-build.outputs.build-qt && 'ON' || 'OFF' }} \
            -DRUN_CLANG_TIDY=OFF
      - name: Make
        run: cmake --build obj --config RelWithDebInfo
      - name: Test
        env:
          TMPDIR: /private/tmp
        run: cmake -E chdir obj ctest --build-config RelWithDebInfo --output-on-failure
      - name: Install
        run: cmake --build obj --config RelWithDebInfo --target install/strip
      - uses: actions/upload-artifact@v3
        with:
          name: binaries-${{ github.job }}
          path: pfx/**/*

  make-src-tarball:
    runs-on: ubuntu-22.04
    needs: [ what-to-build ]
    if: needs.what-to-build.outputs.build-code
    steps:
       - name: Get Dependencies
         run: |
           set -ex
           sudo apt-get update
           sudo apt-get install -y --no-install-recommends \
             ca-certificates \
             cmake \
             libcurl4-openssl-dev \
             libssl-dev \
             ninja-build
       - name: Get Source
         uses: actions/checkout@v3
         with:
           path: src
           submodules: recursive
       - name: Configure
         run: |
           cmake \
             -S src \
             -B obj \
             -G Ninja
       - name: Create source tarball
         run: cmake --build obj --target package_source
       - uses: actions/upload-artifact@v3
         with:
           name: src-tarball
           path: obj/transmission*.tar.*

  macos-from-tarball:
    needs: [ make-src-tarball, what-to-build ]
    if: needs.what-to-build.outputs.build-code
    runs-on: macos-latest
    steps:
      - name: Get Dependencies
        run: |
          set -ex
          brew install \
            cmake \
            gettext \
            gtkmm3 \
            libdeflate \
            libevent \
            libnatpmp \
            libpsl \
            miniupnpc \
            ninja \
            qt@5
      - name: Get Source
        uses: actions/download-artifact@v3
        with:
          name: src-tarball
      - name: Extract Source
        run: mkdir src && tar xf transmission*.tar.* -C src --strip-components 1
      - name: Configure
        run: |
          cmake \
            -S src \
            -B obj \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_INSTALL_PREFIX=pfx \
            -DCMAKE_OSX_ARCHITECTURES='x86_64' \
            -DCMAKE_OSX_DEPLOYMENT_TARGET='10.10' \
            -DCMAKE_PREFIX_PATH=`brew --prefix`/opt/qt@5 \
            -DENABLE_CLI=${{ needs.what-to-build.outputs.build-cli && 'ON' || 'OFF' }} \
            -DENABLE_GTK=${{ needs.what-to-build.outputs.build-gtk && 'ON' || 'OFF' }} \
            -DENABLE_MAC=${{ needs.what-to-build.outputs.build-mac && 'ON' || 'OFF' }}  \
            -DENABLE_QT=${{ needs.what-to-build.outputs.build-qt && 'ON' || 'OFF' }} \
            -DRUN_CLANG_TIDY=OFF
      - name: Make
        run: cmake --build obj --config RelWithDebInfo
      - name: Test
        env:
          TMPDIR: /private/tmp
        run: cmake -E chdir obj ctest --build-config RelWithDebInfo --output-on-failure
      - name: Install
        run: cmake --build obj --config RelWithDebInfo --target install/strip
      - uses: actions/upload-artifact@v3
        with:
          name: binaries-${{ github.job }}
          path: pfx/**/*

  debian-11-from-tarball:
    needs: [ make-src-tarball, what-to-build ]
    if: needs.what-to-build.outputs.build-code
    runs-on: ubuntu-22.04
    container:
      image: debian:11-slim
    steps:
      - name: Get Dependencies
        run: |
          set -ex
          apt-get update
          apt-get install -y --no-install-recommends \
            ca-certificates \
            cmake \
            g++ \
            gettext \
            git \
            libcurl4-openssl-dev \
            libdeflate-dev \
            libevent-dev \
            libfmt-dev \
            libglibmm-2.4-dev \
            libgtkmm-3.0-dev \
            libminiupnpc-dev \
            libnatpmp-dev \
            libpsl-dev \
            libssl-dev \
            ninja-build \
            qtbase5-dev \
            qttools5-dev \
            xz-utils
      - name: Get Source
        uses: actions/download-artifact@v3
        with:
          name: src-tarball
      - name: Extract Source
        run: mkdir src && tar xf transmission*.tar.* -C src --strip-components 1
      - name: Configure
        run: |
          cmake \
            -S src \
            -B obj \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_INSTALL_PREFIX=pfx \
            -DENABLE_CLI=${{ needs.what-to-build.outputs.build-cli && 'ON' || 'OFF' }} \
            -DENABLE_GTK=${{ needs.what-to-build.outputs.build-gtk && 'ON' || 'OFF' }} \
            -DENABLE_MAC=OFF \
            -DENABLE_QT=${{ needs.what-to-build.outputs.build-qt && 'ON' || 'OFF' }} \
            -DRUN_CLANG_TIDY=OFF
      - name: Build
        run: cmake --build obj --config RelWithDebInfo
      - name: Test
        run: cmake -E chdir obj ctest --build-config RelWithDebInfo --output-on-failure
      - name: Install
        run: cmake --build obj --config RelWithDebInfo --target install/strip
      - uses: actions/upload-artifact@v3
        with:
          name: binaries-${{ github.job }}
          path: pfx/**/*
