name: sanitizer-test-clang
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
env:
  GTEST_OUTPUT: xml:./
jobs:
  sanitizer-test-clang:
    runs-on: ubuntu-22.04
    steps:
      - name: get-source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: src
          submodules: recursive
      - name: test-for-diffs
        id: test-for-diffs
        run: |
          set +e
          git -C "${GITHUB_WORKSPACE}/src" diff origin/main -- CMakeLists.txt libtransmission tests third-party utils
          git -C "${GITHUB_WORKSPACE}/src" diff --quiet origin/main -- CMakeLists.txt libtransmission tests third-party utils
          echo "::set-output name=changed::$?"
          echo "hello set-output name=changed::$?"
          set -e
      - name: show-test-results
        run: echo "${{ steps.test-for-diffs.outputs.changed }}"
      - name: get-deps 
        if: steps.test-for-diffs.outputs.changed == '1'
        run: |
          set -ex
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            ca-certificates \
            clang \
            cmake \
            gettext \
            libcurl4-openssl-dev \
            libdeflate-dev \
            libevent-dev \
            libfmt-dev \
            libminiupnpc-dev \
            libnatpmp-dev \
            libpsl-dev \
            libssl-dev \
            ninja-build
      - name: configure
        if: steps.test-for-diffs.outputs.changed == '1'
        run: |
          cmake \
            -S src \
            -B build-clang \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_CXX_COMPILER='clang++' \
            -DCMAKE_CXX_FLAGS='-gdwarf-4 -fno-omit-frame-pointer -fsanitize=address,leak,undefined' \
            -DCMAKE_C_COMPILER='clang' \
            -DCMAKE_C_FLAGS='-gdwarf-4 -fno-omit-frame-pointer -fsanitize=address,leak,undefined' \
            -DCMAKE_INSTALL_PREFIX=pfx \
            -DENABLE_CLI=OFF \
            -DENABLE_GTK=OFF \
            -DENABLE_QT=OFF \
            `#-DENABLE_WEB=ON`
      - name: build
        if: steps.test-for-diffs.outputs.changed == '1'
        run: cmake --build build-clang --config Debug --target libtransmission-test transmission-show
      - name: test
        if: steps.test-for-diffs.outputs.changed == '1'
        run: cmake -E chdir build-clang ctest --build-config Debug --output-on-failure
